# SPDX-License-Identifier: MIT
---
# Here is the right place to put the role's input variables.
# This file also serves as a documentation for such a variables.

crypto_policies_policy:
crypto_policies_reload: true
crypto_policies_reboot_ok: false
