apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
  namespace: default
  labels:
    app: shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      imagePullSecrets: 
        - name: gitlab-registry
      containers:
        - name: shop-container
          image: registry.{{ team_number }}.rust.energy/rust-energy/shop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
