apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-ingress
  namespace: default
spec:
  ingressClassName: haproxy
  rules:
  - host: shop.{{ team_number }}.rust.energy
    http:
      paths:
      - backend:
          service:
            name: shop
            port:
              number: 8080
        path: /
        pathType: Prefix
