---
- name: Install Kubectl
  ansible.builtin.apt:
    name: kubectl=1.28.*
    state: present
    force: true

- name: Create an empty file for Kubeadm configuring
  ansible.builtin.copy:
    content: ""
    dest: /etc/kubernetes/kubeadm-config.yaml
    force: false
    mode: "0600"

- name: Configuring the container runtime including its cgroup driver
  ansible.builtin.blockinfile:
    path: /etc/kubernetes/kubeadm-config.yaml
    block: |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: InitConfiguration
      nodeRegistration:
        criSocket: {{ cri_socket }}
      ---
      kind: ClusterConfiguration
      apiVersion: kubeadm.k8s.io/v1beta3
      networking:
        podSubnet: "10.244.0.0/16"
        serviceSubnet: "10.96.0.0/12"
      ---
      kind: KubeletConfiguration
      apiVersion: kubelet.config.k8s.io/v1beta1
      runtimeRequestTimeout: "15m"
      cgroupDriver: "systemd"
      systemReserved:
        cpu: 100m
        memory: 350M
      kubeReserved:
        cpu: 100m
        memory: 50M
      enforceNodeAllocatable:
      - pods

- name: Create .kube directory
  become: true
  become_user: ubuntu
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: "0755"
