---
- name: domain_create.yaml
  hosts: win_dc
  gather_facts: false

  tasks:
    - name: set ntp servers
      win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ntp_servers}}"'

    - name: Configure Time Zone to Eastern Standard Time
      community.windows.win_timezone:
        timezone: Eastern Standard Time

    - name: Update Hostname Configuration"
      win_hostname:
        name: "{{ hostname }}"
      register: res_win_hostname
    
    - name: Reboot Host to Apply Hostname Changes
      ansible.windows.win_reboot:
      when: res_win_hostname.reboot_required

    - name: Establish New Active Directory Domain
      microsoft.ad.domain:
        dns_domain_name: "{{ adserver_domain }}"
        safe_mode_password: "{{ ansible_password }}"
        reboot: false
      register: domain_create
    
    - name: Reboot host if install requires it
      ansible.windows.win_reboot:
      when: domain_create.reboot_required

      # after reboot, the some services isn't available immediately, we need
      # to retry until this succeeeds
    - name: Create black-team user
      microsoft.ad.user:
        name: black-team
        firstname: Black
        lastname: Team
        display_name: Black Team
        description: DO NOT TOUCH THIS ACCOUNT
        sam_account_name: black-team
        upn: "black-team@{{ adserver_domain }}"
        password: PASSWORD
        groups:
          set:
          - Domain Admins
          - Domain Users
          - Enterprise Admins
        state: present
      register: domain_create_user_result
      retries: 30
      delay: 15
      until: domain_create_user_result is successful