---
roles:
  - name: geerlingguy.swap
    version: "1.2.0"
  - name: geerlingguy.elasticsearch
    version: "5.1.1"
  - name: geerlingguy.kibana
    version: "4.0.2"
  - name: geerlingguy.java
    version: "2.3.2"
  - name: geerlingguy.pip
    version: "3.0.2"
  - name: geerlingguy.docker
    version: "7.1.0"
  - name: geerlingguy.gitlab
    version: "3.2.0"

collections:
  - name: freeipa.ansible_freeipa
    version: "1.12.0"
  - name: chocolatey.chocolatey
    version: "1.5.1"
  - name: microsoft.ad
    version: "1.4.1"
