---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fun
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: './'
    repoURL: git@gitlab.{{ team_number }}.rust.energy:rust-energy/fun.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: git@gitlab.{{ team_number }}.rust.energy:rust-energy/shop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
